redis = "12800"

[train]
resume = false
epoch = 1
output_dir = "./outputs/gpt-oss-20b-p-fsdp4-r-tp4-pp1-grpo"
epsilon = 1e-6
optm_name = "AdamW"
optm_lr = 1e-6
optm_impl = "fused"
optm_weight_decay = 0.01
optm_betas = [ 0.9, 0.999,]
optm_warmup_steps = 20
optm_grad_norm_clip = 1.0
async_tp_enabled = false
compile = false
master_dtype="bfloat16"
param_dtype = "bfloat16"
fsdp_reduce_dtype = "float32"
fsdp_offload = false
fsdp_reshard_after_forward = "default"
train_batch_per_replica = 128
sync_weight_interval = 1

[rollout]
gpu_memory_utilization = 0.5
enable_chunked_prefill = true
n_generation = 16
batch_size = 8
quantization = "mxfp4"
max_response_length = 1024


[policy]
model_name_or_path = "openai/gpt-oss-20b"
model_max_length = 4096
model_gradient_checkpointing = true

[logging]
logger = ['console', 'wandb']
project_name = "cosmos_rl"
experiment_name = "None"

[train.train_policy]
type = "grpo"
dataset.name = "openai/gsm8k"
dataset.subset = "main"
dataset.split = "train"
prompt_column_name = "question"
response_column_name = "answer"
reward_function = "gsm8k"
temperature = 0.9
epsilon_low = 0.2
epsilon_high = 0.2
kl_beta = 0.0
mu_iterations = 1
min_filter_prefix_tokens = 1
mini_batch = 1
on_policy = true


[train.ckpt]
enable_checkpoint = true
save_freq = 30000
save_mode = "async"

[rollout.parallelism]
n_init_replicas = 1
tp_size = 4
cp_size = 1
dp_shard_size = 1
pp_size = 1
dp_replicate_size = 1


[policy.parallelism]
n_init_replicas = 1
tp_size = 1
cp_size = 1
dp_shard_size = 4
pp_size = 1
dp_replicate_size = 1
