name: build-and-test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: Compute Vars
        id: vars
        run: |
          echo "image_tag=${{ github.repository }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build image
        run: |
          docker build -t ${{ steps.vars.outputs.image_tag }} .

      - name: Run tests
        id: tests
        run: |
          set -ex

          container_id=$(docker run -t -d --rm \
            --gpus all \
            --shm-size=24G \
            -v ${{ github.workspace }}/tests:/workspace/cosmos-rl/tests:ro \
            -e PYTHONPYCACHEPREFIX=/tmp/pycache \
            -w /workspace/cosmos-rl \
            ${{ steps.vars.outputs.image_tag }} /bin/bash)

          echo "container_id=${container_id}" >> $GITHUB_OUTPUT
          DOCKER_RUN="timeout 10m docker exec ${container_id}"
          LONG_DOCKER_RUN="timeout 15m docker exec ${container_id}"

          ${DOCKER_RUN} python -c "from cosmos_rl._version import version; print(version)"

          # run tests
          ${DOCKER_RUN} python tests/test_cosmos_hf_precision.py
          ${DOCKER_RUN} /bin/bash -c "CP_SIZE=2 TP_SIZE=1 DP_SIZE=2 torchrun --nproc_per_node=4 tests/test_context_parallel.py"
          ${DOCKER_RUN} python tests/test_cache.py
          ${DOCKER_RUN} python tests/test_comm.py
          ${DOCKER_RUN} python tests/test_fp8.py
          ${DOCKER_RUN} python tests/test_lora.py
          # ${DOCKER_RUN} python tests/test_grad_allreduce.py
          ${DOCKER_RUN} python tests/test_high_availability_nccl.py
          ${DOCKER_RUN} python tests/test_nccl_collectives.py
          ${DOCKER_RUN} python tests/test_nccl_timeout.py
          ${DOCKER_RUN} python tests/test_parallel_map.py
          ${DOCKER_RUN} python tests/test_policy_to_policy.py
          ${DOCKER_RUN} python tests/test_policy_to_rollout.py
          ${DOCKER_RUN} python tests/test_process_flow.py
          ${DOCKER_RUN} python tests/test_math_verify.py
          ${DOCKER_RUN} python tests/test_policy_overfit.py
          ${DOCKER_RUN} python tests/test_data_packer.py
          ${DOCKER_RUN} python tests/test_sequence_packing.py
          ${LONG_DOCKER_RUN} python tests/test_integration.py --stream

      - name: Cleanup
        if: always()
        run: |
          docker stop "${{ steps.tests.outputs.container_id }}" || true
          docker rmi -f "${{ steps.vars.outputs.image_tag }}" || true
